### ISSUE TITLE
Binding EventEmitter class for custom events

### ISSUE THREAD

**Issue by woeps** [sikanhe/reason-node#26]
Regarding [`Stream`s](https://nodejs.org/api/stream.html) (bound in [ReasonNode.Stream](https://github.com/sikanhe/reason-node/blob/master/src/Stream.re)) and them being instances of the [`EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter) class:
How would you handle (`emit` and `on`) for custom events?
There are several parser (and other libs) in the node eco-system leveraging custom events. How would you bind those libraries using `ReasonNode.Stream`? Separate custom binding of `on` for each?

I understand it's complicated (if even possible) to find a generic solution due to the polymorphism of the `EventEmitter` class. I'd like to know your thoughts and ideas on this topic.

Thank you both for your huge efforts and amazing work!

**Comment by austindd** [comment]
Thanks for bringing up this issue, @woeps . As you mentioned in the Discord channel, it is a bit complicated to create generic bindings for `EventEmitter`. I attempted to write such bindings early on, but it became clear to me that it would be very difficult. I think @sikanhe would agree.

At one point, I started to build a chart of each built-in `EventEmitter` subclass, the specific events they emitted, and the type signatures of their `on` and `emit` functions for each case. I found that in many cases, the arity of those functions was inconsistent. Even for two separate `EventEmitter` subclasses emitting the same event, they would expect different callback signatures.

There might be a way to implement the `on` and `emit` functions using functors to provide the correct type signatures. I'll see if I can come up with an example.

In either case, it might be just as much work for the user to implement their own custom bindings from scratch. But I'm completely open to suggestions.

**Comment by austindd** [comment]
@woeps Here is an example of how to provide a reasonable API for generating the `EventEmitter.on` function. It compiles and works correctly with the current version of this library.

```reason
module EventEmitter = {
  module On = {
    module Impl =
           (
             T: {
               type t;
               type event('a);
               let eventToString: event('a) => string;
             },
           ) => {
      [@bs.send] external on: (T.t, string, 'a) => unit = "on";
      let on: type a b. (T.t, T.event(a => b), a => b) => unit =
        (eventEmitter, event, callback) => {
          let eventString = T.eventToString(event);
          on(eventEmitter, eventString, callback);
        };
    };
  };
};

module MyEmitter = {
  type t = Stream.Readable.t(Buffer.t);
  type event(_) =
    | Data: event(Buffer.t => unit)
    | Error: event(Js.Exn.t => unit)

  include EventEmitter.On.Impl({
    type nonrec t = t;
    type nonrec event('a) = event('a);
    let eventToString: type a. event(a) => string =
      fun
      | Data => "data"
      | Error => "error"
  });
};

let (stdin, stdout) = Process.(stdin(process), stdout(process));

/** echo input from the terminal */
let () =
  MyEmitter.(
    stdin->on(Data, buffer => {Stream.write(stdout, buffer)->ignore})
  );
```

**Comment by austindd** [comment]
This allows you to use (GADT) variants as event names, and to implement custom callback type signatures for each event. The final API looks really nice, IMO.

There are downsides to this approach, including runtime performance costs, a minor increase in bundle size, and the usual complexity of using functors and GADT's in your code.

I'm not sure the benefits outweigh the costs here, but it's an option.

**Comment by woeps** [comment]
This looks pretty nice to me!
It's definitely not a zero-cost binding anymore, that's true. I see why you would be hesitant to include such bindings in this library. 
Personally, I'd still use such a binding. It feels good to have the compiler on my team even in this case. I wouldn't worry too much about a recognizable performance hit.

I'm wondering, if it's possible to use Bucklescript's `@unboxed` feature to get rid of `eventToString` and just define the event like ` | Data("data"): event(Buffer.t => unit)`.

**edit:** I was mixing up types and values. the event could only be defined as `| Data(string): event(Buffer.t => unit)`. Which means the actual values would have to be added to `MyEmitter`. On the other hand, the shadowing `on` could be removed. So package size would be roughly the same compared to your version, but without the extra function call.
I haven't used `@unboxed` before.. in a first try on the reason-playground I got an array of the string instead of the string itself.
I will try to find some more time to come up with a working example.

**Comment by austindd** [comment]
@woeps Yeah, it would be nice to be able to use `@unboxed` type as a GADT with multiple variant constructors, but unfortunately, `@unboxed` only allows us to use a single constructor, which prohibits us from having multiple callback signatures.

As for the extra function call, it's not a huge deal, especially since adding/removing event listeners is rarely performed in a hot path. Even the `emit` function will not have to serialize/deserialize anything when it is called internally (any explicit calls to `emit` by the user would require the event type to be serialized to string for each call).

My main concern is more about scope creep than anything else. We strongly prefer zero-cost bindings where possible, and encourage other library authors to implement "idiomatic Reason" abstractions on top of it.

However, since `EventEmitter` is such a critical and pervasive class that is sub-classed by a lot of user-land code in the Node ecosystem, it might make sense to make an exception here. @sikanhe may have different views on this, but I think it's worth considering.

**Comment by austindd** [comment]
For now, I think it would be a good idea to create a PR to experiment with the implementation. Even if we decide not to include it in the final library, it would be nice to have something like this in the ecosystem.

**Comment by sikanhe** [comment]
agreed with @austindd A PR is welcome to help us talk about something more concrete

**Comment by austindd** [comment]
@woeps @sikanhe 

Here is an interesting way of accomplishing the same thing with effectively zero-cost bindings:

```reason
module EventEmitter = {
  module Impl = (T: {
                   type t;
                   type event('a) = pri string;
                 }) => {
    [@bs.send]
    external on: (T.t, T.event('a => 'b), 'a => 'b) => unit =
      "on";

    [@bs.send]
    external off: (T.t, T.event('a => 'b), 'a => 'b) => unit =
      "off";

    [@bs.send] external emit: (T.t, T.event('a => 'b), 'a) => unit = "emit";
  };
};

module MyEmitter = {
  type t = Stream.Readable.t(Buffer.t);
  type event('a) = pri string;

  let data: event(Buffer.t => unit) = Obj.magic("data");
  let error: event(Js.Exn.t => unit) = Obj.magic("error");

  include EventEmitter.Impl({
    type nonrec t = t;
    type nonrec event('a) = event('a);
  });
};

let (stdin, stdout) = Process.(stdin(process), stdout(process));

let () = {
  MyEmitter.(
    stdin->on(data, buffer => {Stream.write(stdout, buffer)->ignore})
  );
};
```
As of `bs-platform v7.3.1`, this compiles to the following JS code:

```js
// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");

function Impl(T) {
  return { };
}

var EventEmitter = {
  Impl: Impl
};

var data = "data";

var MyEmitter = {
  data: data,
  error: "error"
};

var stdin = Process.stdin;

var stdout = Process.stdout;

stdin.on(data, (function (buffer) {
        stdout.write(buffer);
        
      }));

exports.EventEmitter = EventEmitter;
exports.MyEmitter = MyEmitter;
exports.stdin = stdin;
exports.stdout = stdout;
/* stdin Not a pure module */

```

This approach avoids using GADT variant types, which eliminates the need for (de-)serialization. This should avoid any runtime overhead, aside from the usual functor artifacts in the JS output. These artifacts should be compiled away with modern bundlers.

The performance should be roughly equivalent to plain, optimized JS. It may even be *faster*, since the 'event name' strings are pre-allocated (although V8 might optimize string literals). So I do like this approach.

Issues: 

- If the user is not expecting to implement an abstract type, then this API might seem a little strange to them. My concern is that the *expected* design pattern is not immediately *obvious* without looking at an example or explanation. But the same argument applies to the GADT solution as well.

Any feedback on this is appreciated!

**Comment by austindd** [comment]
@woeps I am currently in a new branch working on a solution that might eliminate the need for the module functor, and might play nicely with our standard subtyping pattern. So we could potentially model `Stream` types as subtypes of `EventEmitter`.

It is still unproven, but I think it will work pretty well.

**Comment by woeps** [comment]
I'd be very interested in your approach. Sounds great so far.

**Comment by austindd** [comment]
Actually, now that I've though more about it, it seems problematic. The main issue is tracking the types of data that can be passed as arguments to event listeners. The `Stream.<Subclass>.t` type is a special case of `EventEmitter` where one or more data types are provided by a type parameter. This is specific to streams and is not possible to generalize across all `EventEmitter` implementations.

In order to track the types of data that are important to a stream, the `event('a => 'b)` type would need extra type parameters that correspond the the subclass and it's own type variables, at least if you want any hope of type safety.

Therefore, it seems to me that the only way to make this work is to use a functor to generate the `EventEmitter` API for a given type `t`. It's really hard to safely encode polymorphic event emitters & callbacks with this design, which is probably a good thing.

The downside is that we cannot implement it such that streams are considered subtypes of `EventEmitter`.

If anyone wants to see code examples of what I'm talking about, I could probably come up with minimal versions of the different designs. But trust me when I say that this is inherently tricky.

**Comment by austindd** [comment]
@woeps I just submitted a PR to add the `EventEmitter` bindings: https://github.com/sikanhe/reason-nodejs/pull/30

Feel free to take a look and offer any feedback or concerns.

**Comment by austindd** [comment]
This should be good to go for the next release. See the code here:
https://github.com/sikanhe/reason-nodejs/blob/release/13.0.0-beta.2/src/EventEmitter.re

**Comment by austindd** [comment]
#30
